/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddUserForm: typeof import('./src/components/user/AddUserForm.vue')['default']
    AnalysisResult: typeof import('./src/components/analysis/AnalysisResult.vue')['default']
    AnimatedTooltip: typeof import('./src/components/ui/animated-tooltip/AnimatedTooltip.vue')['default']
    CardBody: typeof import('./src/components/ui/card-3d/CardBody.vue')['default']
    CardContainer: typeof import('./src/components/ui/card-3d/CardContainer.vue')['default']
    CardItem: typeof import('./src/components/ui/card-3d/CardItem.vue')['default']
    ContainerScroll: typeof import('./src/components/ContainerScroll.vue')['default']
    ContainerScrollCard: typeof import('./src/components/ContainerScrollCard.vue')['default']
    ContainerScrollTitle: typeof import('./src/components/ContainerScrollTitle.vue')['default']
    CosmicPortal: typeof import('./src/components/CosmicPortal.vue')['default']
    DefaultCursor: typeof import('./src/components/ui/smooth-cursor/DefaultCursor.vue')['default']
    Dock: typeof import('./src/components/ui/dock/Dock.vue')['default']
    DockIcon: typeof import('./src/components/ui/dock/DockIcon.vue')['default']
    DockSeparator: typeof import('./src/components/ui/dock/DockSeparator.vue')['default']
    FeatureGallery: typeof import('./src/components/FeatureGallery.vue')['default']
    FlipWords: typeof import('./src/components/ui/flip-words/FlipWords.vue')['default']
    FluidAuroraCursor: typeof import('./src/components/FluidAuroraCursor.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HistoryList: typeof import('./src/components/analysis/HistoryList.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginForm: typeof import('./src/components/user/LoginForm.vue')['default']
    Marquee: typeof import('./src/components/ui/marquee/Marquee.vue')['default']
    ParamSettings: typeof import('./src/components/Admin/ParamSettings.vue')['default']
    ParentSize: typeof import('./src/components/ui/spline/ParentSize.vue')['default']
    RegisterForm: typeof import('./src/components/user/RegisterForm.vue')['default']
    ReviewCard: typeof import('./src/components/ui/marquee/ReviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmoothCursor: typeof import('./src/components/ui/smooth-cursor/SmoothCursor.vue')['default']
    Spline: typeof import('./src/components/ui/spline/Spline.vue')['default']
    Text3d: typeof import('./src/components/ui/text-3d/Text3d.vue')['default']
    UploadPanel: typeof import('./src/components/analysis/UploadPanel.vue')['default']
    UserForm: typeof import('./src/components/user/UserForm.vue')['default']
    UserManager: typeof import('./src/components/Admin/UserManager.vue')['default']
  }
}
